### ISSUE TITLE
Console Setup: Doesn't seem to work with OpenShift Origin v1.5.0-alpha.0

### ISSUE THREAD

**Issue by zak-hassan** [radanalyticsio/oshinko-console#40]
Ran into issues with v1.5.0-alpha.0

The extension doesn't display in the console.

**Comment by sub-mod** [comment]
does grunt build throw any errors ?

**Comment by zak-hassan** [comment]
chad and I ran into this before and we had to roll back to 1.4.0

**Comment by zak-hassan** [comment]
No its more on the server not displaying the extension in the console.

**Comment by crobby** [comment]
I believe my problem was related to my configuration and I made mistakes. I think this should be closed.  if you disagree, please re-open.
